### PR TITLE
Non-isotropic length scales for graph-based Gaussian processes

### PR DESCRIPTION
**Pull request by tillahoffmann**
This PR allows graph-based Gaussian processes to have different length scales along different dimensions of the covariate space.

### CODE REVIEW

**Comment by tillahoffmann** [comment]
On hold until fix from https://github.com/stan-dev/math/pull/3084 is released.

**Comment by skiptoniam** [comment]
@tillahoffmann has this been updated? for the stan libs?

**Comment by tillahoffmann** [comment]
Quick update: it looks like the new release date for the bugfix we need is November 11 (see [here](https://discourse.mc-stan.org/t/planning-the-2-36-release/36382/6) for details).

**Comment by tillahoffmann** [comment]
It looks like the next release date has been pushed back to late November/early Decembers so we'll have to wait a little longer to merge this feature.

**Comment by tillahoffmann** [comment]
We'll have to weight for the next release candidate because the `_jacobian` suffix for functions is no longer allowed by accident (see [here](https://discourse.mc-stan.org/t/planning-the-2-36-release/36382/16) for details).

**Comment by tillahoffmann** [comment]
@skiptoniam, thanks for the patience with this PR. I'll release a new Python package shortly and also port the changes over to the [R package](https://cran.r-project.org/package=gptoolsStan). I'll post another update here once that's done.

**Pull request merged**
